import os

SQLALCHEMY_DATABASE_URI = os.environ.get("SQLALCHEMY_DATABASE_URI")
SECRET_KEY = os.environ.get("SUPERSET_SECRET_KEY", "supersecretkey123")

WTF_CSRF_ENABLED = True
ROW_LIMIT = 5000
SUPERSET_WEBSERVER_PORT = 8088
