COLUMN_MAPPING = {
    "Номер реестровой записи контракта": "registry_contract_id",
    "Заказчик: наименование": "customer_name",
    "Заказчик: ИНН": "customer_inn",
    "Заказчик: КПП": "customer_kpp",
    "Уровень бюджета": "budget_level",
    "Источник финансирования контракта: наименование бюджета": "budget_source_name",
    "Источник финансирования контракта: наименование/вид внебюджетных средств": "extra_budget_source_type",
    "Способ размещения заказа": "procurement_method",
    "Номер извещения о проведени торгов": "notice_number",
    "Дата подведения результатов определения поставщика (подрядчика, исполнителя)": "supplier_result_date",
    "Реквизиты документа, подтверждающего основание заключения контракта": "basis_document_details",
    "Контракт: дата": "contract_date",
    "Контракт: номер": "contract_number",
    "Предмет контракта": "contract_subject",
    "Цена контракта": "contract_price",
    "Код бюджетной классификации": "budget_classification_code",
    "КОСГУ": "kosgu_code",
    "КВР": "kvr_code",
    "Идентификационный код закупки (ИКЗ)": "ikz_code",
    "Объект закупки: наименование товаров, работ, услуг": "purchase_object_name",
    "Объект закупки: код позиции": "purchase_object_code",
    "Объект закупки: цена за единицу, рублей": "unit_price_rub",
    "Объект закупки: количество поставленных товаров, выполненных работ, оказанных услуг": "delivered_quantity",
    "Объект закупки: сумма, рублей": "purchase_object_amount_rub",
    "Информация о поставщиках (исполнителях, подрядчиках) по контракту: наименование юридического лица (ф.и.о. физического лица)": "supplier_name",
    "Информация о поставщиках (исполнителях, подрядчиках) по контракту: ИНН": "supplier_inn",
    "Информация о поставщиках (исполнителях, подрядчиках) по контракту: КПП": "supplier_kpp",
    "Дата последнего изменения записи": "last_modified_date",
    "Дата исполнения контракта: по контракту": "contract_execution_date",
    "source_file": "source_file",
}

REQUIRED_COLUMNS = [
    "registry_contract_id", "customer_name", "customer_inn", "customer_kpp", "budget_level",
    "budget_source_name", "extra_budget_source_type", "procurement_method", "notice_number",
    "supplier_result_date", "basis_document_details", "contract_date", "contract_number",
    "contract_subject", "contract_price", "budget_classification_code", "kosgu_code", "kvr_code",
    "ikz_code", "purchase_object_name", "purchase_object_code", "unit_price_rub", "delivered_quantity",
    "purchase_object_amount_rub", "supplier_name", "supplier_inn", "supplier_kpp",
]
